name: Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.TOKEN }}
      - run: docker build -t ghcr.io/$GITHUB_ACTOR/pepic:latest .
      - run: docker image push ghcr.io/$GITHUB_ACTOR/pepic:latest
